// Name pools for generated recruits. ~250 × ~380 seeded combinations; the
// generator avoids exact duplicates within a class.

import type { Rng } from "../../engine/rng.ts";
import { pick } from "../../engine/rng.ts";

const FIRST = [
  "Aaron", "Adrian", "Aiden", "AJ", "Alex", "Amari", "Andre", "Andrew", "Anthony", "Antonio",
  "Ashton", "Austin", "Avery", "Blake", "Bo", "Brady", "Brandon", "Braxton", "Brayden", "Brendan",
  "Brian", "Brock", "Bryce", "Byron", "Caden", "Caleb", "Cam", "Camden", "Cameron", "Carlos",
  "Carson", "Carter", "Cayden", "Cedric", "Chad", "Chance", "Charlie", "Chase", "Chris", "Christian",
  "CJ", "Cole", "Colin", "Colton", "Connor", "Cooper", "Corey", "Cortez", "Curtis", "DaQuan",
  "Dallas", "Dalton", "Damian", "Damien", "Damon", "Dante", "Daniel", "Darius", "Darnell", "Darren",
  "David", "Davion", "Dawson", "DeAndre", "Deion", "DeMarcus", "Demetrius", "Denzel", "Deon", "Derek",
  "Derrick", "Deshawn", "Desmond", "Devin", "Devon", "DJ", "Dominic", "Donovan", "Dorian", "Drew",
  "Duke", "Dylan", "Earl", "Easton", "Eddie", "Eli", "Elijah", "Emmanuel", "Emmett", "Eric",
  "Ethan", "Evan", "Ezekiel", "Felix", "Frank", "Gabe", "Gabriel", "Gage", "Garrett", "Gavin",
  "George", "Grant", "Grayson", "Greg", "Griffin", "Gunnar", "Harrison", "Hayden", "Henry", "Hudson",
  "Hunter", "Ian", "Isaac", "Isaiah", "Israel", "Ivan", "Jabari", "Jace", "Jack", "Jackson",
  "Jacob", "Jaden", "Jake", "Jalen", "Jamal", "Jamar", "James", "Jamie", "Jared", "Jarrett",
  "Jason", "Javon", "Jaxon", "Jaxson", "Jay", "Jayden", "Jaylen", "Jaylin", "JD", "Jeremiah",
  "Jeremy", "Jermaine", "Jesse", "Jett", "Jimmy", "Joe", "Joel", "John", "Johnny", "Jonah",
  "Jonathan", "Jordan", "Joseph", "Josh", "Joshua", "Josiah", "JT", "Juan", "Judah", "Julian",
  "Julius", "Justin", "Justice", "Kaden", "Kai", "Kaleb", "Kameron", "Kayden", "Keegan", "Keith",
  "Kendall", "Kendrick", "Kevin", "Khalil", "Kingston", "Kobe", "Kolton", "Kyler", "Kyle", "Lamar",
  "Landon", "Lane", "Larry", "Lawrence", "Leon", "Levi", "Liam", "Lincoln", "Logan", "Louis",
  "Luca", "Lucas", "Luke", "Malachi", "Malcolm", "Malik", "Marcus", "Mario", "Mark", "Marquis",
  "Marshall", "Martin", "Marvin", "Mason", "Matthew", "Maurice", "Maverick", "Max", "Maxwell", "Micah",
  "Michael", "Miguel", "Miles", "Mitchell", "Mo", "Montrell", "Morgan", "Moses", "Nasir", "Nate",
  "Nathan", "Nathaniel", "Nick", "Nico", "Noah", "Nolan", "Omar", "Otis", "Owen", "Parker",
  "Patrick", "Paul", "Peyton", "Phillip", "Preston", "Quentin", "Quincy", "Quinn", "Rashad", "Ray",
  "Reggie", "Reid", "Rex", "Ricky", "Riley", "Robert", "Rocco", "Roman", "Ronald", "Ryan",
  "Ryder", "Sam", "Samuel", "Santino", "Saul", "Sean", "Sebastian", "Seth", "Shane", "Shaun",
  "Silas", "Simeon", "Solomon", "Spencer", "Stephen", "Sterling", "Tanner", "Tariq", "Tate", "Taylor",
  "Terrance", "Terrell", "Terry", "Theo", "Thomas", "Timothy", "TJ", "Tobias", "Todd", "Tommy",
  "Trace", "Travis", "Trent", "Trenton", "Trevon", "Trevor", "Trey", "Tristan", "Troy", "Tucker",
  "Ty", "Tyler", "Tyrell", "Tyrese", "Tyrone", "Tyson", "Victor", "Vince", "Walker", "Warren",
  "Wesley", "Weston", "Will", "William", "Wyatt", "Xavier", "Zach", "Zachary", "Zaire", "Zane",
];

const LAST = [
  "Abbott", "Acosta", "Adams", "Alexander", "Allen", "Alvarez", "Anderson", "Andrews", "Archer", "Armstrong",
  "Arnold", "Atkins", "Austin", "Bailey", "Baker", "Baldwin", "Banks", "Barber", "Barnes", "Barrett",
  "Bass", "Bates", "Battle", "Baxter", "Beasley", "Beck", "Bell", "Bennett", "Benson", "Berry",
  "Bishop", "Black", "Blackwell", "Blair", "Blake", "Bolden", "Bond", "Booker", "Boone", "Bowen",
  "Bowman", "Boyd", "Boykin", "Bradford", "Bradley", "Brady", "Branch", "Brewer", "Bridges", "Briggs",
  "Bright", "Brock", "Brooks", "Brown", "Bruce", "Bryant", "Buchanan", "Buckner", "Burke", "Burnett",
  "Burns", "Burton", "Bush", "Butler", "Byrd", "Cain", "Caldwell", "Calhoun", "Campbell", "Cannon",
  "Carey", "Carr", "Carroll", "Carson", "Carter", "Case", "Chambers", "Chandler", "Chapman", "Charles",
  "Chase", "Chavez", "Cherry", "Church", "Clark", "Clay", "Clayton", "Clemons", "Cobb", "Cole",
  "Coleman", "Collier", "Collins", "Combs", "Conner", "Cook", "Cooper", "Copeland", "Cortez", "Cox",
  "Craig", "Crawford", "Cross", "Cruz", "Cummings", "Cunningham", "Curry", "Curtis", "Dalton", "Daniels",
  "Davenport", "Davidson", "Davis", "Dawson", "Day", "Dean", "Delgado", "Dennis", "Diaz", "Dickerson",
  "Dillard", "Dixon", "Dodson", "Donaldson", "Dorsey", "Douglas", "Doyle", "Drake", "Dudley", "Duke",
  "Duncan", "Dunn", "Duran", "Durham", "Eaton", "Edwards", "Elliott", "Ellis", "Ellison", "Emerson",
  "English", "Erickson", "Espinoza", "Estes", "Evans", "Everett", "Ewing", "Farley", "Farmer", "Faulkner",
  "Ferguson", "Fields", "Finley", "Fisher", "Fitzgerald", "Fleming", "Fletcher", "Flores", "Floyd", "Foley",
  "Ford", "Foster", "Fowler", "Fox", "Francis", "Franklin", "Frazier", "Freeman", "French", "Frost",
  "Fuller", "Gaines", "Gallagher", "Garcia", "Gardner", "Garner", "Garrett", "Garrison", "Gates", "Gentry",
  "George", "Gibbs", "Gibson", "Gilbert", "Giles", "Gill", "Gilmore", "Glass", "Glenn", "Glover",
  "Goodman", "Goodwin", "Gordon", "Grady", "Graham", "Grant", "Graves", "Gray", "Green", "Greer",
  "Gregory", "Griffin", "Griffith", "Grimes", "Gross", "Guerrero", "Gutierrez", "Guzman", "Hale", "Haley",
  "Hall", "Hamilton", "Hammond", "Hampton", "Hancock", "Haney", "Hardin", "Harding", "Hardy", "Harmon",
  "Harper", "Harrell", "Harrington", "Harris", "Harrison", "Hart", "Harvey", "Hawkins", "Hayden", "Hayes",
  "Haynes", "Heath", "Henderson", "Hendrix", "Henry", "Hensley", "Herman", "Hernandez", "Herring", "Hess",
  "Hester", "Hicks", "Higgins", "Hill", "Hines", "Hobbs", "Hodges", "Hogan", "Holland", "Holloway",
  "Holmes", "Holt", "Hood", "Hooper", "Hoover", "Hopkins", "Horn", "Horne", "Horton", "House",
  "Houston", "Howard", "Howell", "Hubbard", "Hudson", "Huff", "Huffman", "Hughes", "Hull", "Humphrey",
  "Hunt", "Hunter", "Hurley", "Hurst", "Hutchinson", "Ingram", "Irwin", "Jackson", "Jacobs", "James",
  "Jarvis", "Jefferson", "Jenkins", "Jennings", "Jensen", "Johns", "Johnson", "Johnston", "Jones", "Jordan",
  "Joseph", "Joyner", "Kane", "Keith", "Keller", "Kelley", "Kelly", "Kemp", "Kennedy", "Kent",
  "Kerr", "Key", "Kidd", "Kim", "King", "Kirby", "Kirk", "Knight", "Knox", "Lamb",
  "Lambert", "Lancaster", "Lane", "Lang", "Langston", "Larson", "Lawrence", "Lawson", "Le", "Leach",
  "Lee", "Leonard", "Lester", "Levine", "Lewis", "Lindsey", "Little", "Livingston", "Lloyd", "Logan",
  "Long", "Lopez", "Love", "Lowe", "Lucas", "Lynch", "Lyons", "Mack", "Madden", "Maddox",
  "Malone", "Mann", "Manning", "Marsh", "Marshall", "Martin", "Martinez", "Mason", "Massey", "Mathis",
  "Matthews", "Maxwell", "May", "Mayes", "Maynard", "Mays", "McBride", "McCall", "McCarthy", "McClain",
  "McCoy", "McCray", "McDaniel", "McDonald", "McDowell", "McGee", "McGuire", "McIntyre", "McKee", "McKenzie",
  "McKinney", "McLaughlin", "McLean", "McMillan", "McNeil", "Meadows", "Medina", "Mejia", "Melton", "Mendez",
  "Mercer", "Merritt", "Meyer", "Michael", "Middleton", "Miles", "Miller", "Mills", "Mitchell", "Monroe",
  "Montgomery", "Moody", "Moon", "Mooney", "Moore", "Morales", "Moran", "Moreno", "Morgan", "Morris",
  "Morrison", "Morrow", "Morton", "Moses", "Mosley", "Moss", "Mullen", "Mullins", "Munoz", "Murphy",
  "Murray", "Myers", "Nash", "Neal", "Nelson", "Newman", "Newton", "Nichols", "Nicholson", "Nixon",
  "Noble", "Nolan", "Norman", "Norris", "Norton", "Norwood", "Nunez", "O'Brien", "O'Connor", "O'Neal",
  "Odom", "Oliver", "Olsen", "Olson", "Ortega", "Ortiz", "Osborne", "Owens", "Pace", "Page",
  "Palmer", "Parker", "Parks", "Parrish", "Parsons", "Pate", "Patel", "Patrick", "Patterson", "Patton",
  "Paul", "Payne", "Payton", "Pearson", "Peck", "Pena", "Pennington", "Perez", "Perkins", "Perry",
  "Peters", "Peterson", "Petty", "Phelps", "Phillips", "Pierce", "Pittman", "Pitts", "Pollard", "Poole",
  "Pope", "Porter", "Potter", "Powell", "Powers", "Pratt", "Preston", "Price", "Prince", "Pruitt",
  "Pugh", "Quinn", "Ramirez", "Ramos", "Ramsey", "Randall", "Randolph", "Rankin", "Ray", "Raymond",
  "Reed", "Reese", "Reeves", "Reid", "Reyes", "Reynolds", "Rhodes", "Rice", "Rich", "Richards",
  "Richardson", "Richmond", "Riddle", "Riggs", "Riley", "Rios", "Rivera", "Rivers", "Roach", "Robbins",
  "Roberson", "Roberts", "Robertson", "Robinson", "Rodgers", "Rodriguez", "Rogers", "Rollins", "Roman", "Rose",
  "Ross", "Roth", "Rowe", "Rowland", "Roy", "Rucker", "Rush", "Russell", "Rutledge", "Ryan",
  "Salazar", "Sampson", "Sanchez", "Sanders", "Sandoval", "Santiago", "Santos", "Saunders", "Savage", "Sawyer",
  "Schmidt", "Scott", "Sears", "Sellers", "Sexton", "Shaffer", "Shannon", "Sharp", "Shaw", "Shelton",
  "Shepherd", "Sheppard", "Sherman", "Shields", "Short", "Simmons", "Simon", "Simpson", "Sims", "Singleton",
  "Skinner", "Slater", "Sloan", "Small", "Smith", "Snider", "Snow", "Snyder", "Solomon", "Sparks",
  "Spears", "Spence", "Spencer", "Stafford", "Stanley", "Stanton", "Stark", "Steele", "Stephens", "Stevens",
  "Stevenson", "Stewart", "Stokes", "Stone", "Stout", "Strickland", "Strong", "Stuart", "Suggs", "Sullivan",
  "Summers", "Sutton", "Swanson", "Sweeney", "Tanner", "Tate", "Taylor", "Terrell", "Terry", "Thomas",
  "Thompson", "Thornton", "Tillman", "Todd", "Torres", "Townsend", "Tran", "Travis", "Trevino", "Tucker",
  "Turner", "Tyler", "Tyson", "Underwood", "Valdez", "Valentine", "Vance", "Vaughn", "Vazquez", "Vega",
  "Velez", "Vincent", "Vinson", "Wade", "Wagner", "Walker", "Wall", "Wallace", "Waller", "Walls",
  "Walsh", "Walter", "Walters", "Walton", "Ward", "Ware", "Warner", "Warren", "Washington", "Waters",
  "Watkins", "Watson", "Watts", "Weaver", "Webb", "Weber", "Webster", "Welch", "Wells", "West",
  "Wheeler", "Whitaker", "White", "Whitfield", "Whitley", "Wiggins", "Wilcox", "Wilder", "Wiley", "Wilkerson",
  "Wilkins", "Wilkinson", "Williams", "Williamson", "Willis", "Wilson", "Winters", "Wise", "Witt", "Wolf",
  "Wolfe", "Wood", "Woodard", "Woods", "Woodson", "Wooten", "Workman", "Wright", "Wyatt", "Yates",
  "York", "Young", "Zimmerman",
];

/** Seeded full name; caller dedupes within a class if desired. */
export function genName(rng: Rng): string {
  return `${pick(FIRST, rng)} ${pick(LAST, rng)}`;
}
